"""Shared limits and defaults for synthetic-hardnlp experiments."""

CONTEXT_MAX_CHARS = 8000
PROMPT_SAVE_MAX_CHARS = 2000
GENERATION_ABS_MAX_CHARS = 600
BATCH_MAX_EXEMPLARS = 10
BATCH_MAX_EXEMPLAR_CHARS = 2000
GENERATION_TEMPERATURE = 0.8
VALIDATOR_TEMPERATURE = 0.0
PARSE_MAX_RETRIES = 3
TARGET_COL = "Domain"
TEXT_FORMAT = "embedder"
CLASSIFIER = "modernbert_linear_probe"
MODERNBERT_MODEL_ID = "answerdotai/ModernBERT-base"
MODERNBERT_MAX_LENGTH = 2048
OLLAMA_MODEL_DEFAULT = "llama3:8b"
SYNTHETIC_CAP_DEFAULT = 250

# SetFit experiment group
SETFIT_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
SETFIT_CLASSIFIER = "setfit"
SETFIT_TRAIN_N = 100
SETFIT_SYNTHETIC_CAP = 30
SETFIT_MAX_ITEMS_PER_REQUEST = 3
GOOGLE_GEMMA_MODEL_DEFAULT = "gemma-4-31b-it"
GOOGLE_FLASH_MODEL_DEFAULT = "gemini-3.1-flash-lite"
SETFIT_UNCERTAINTY_LOW = 0.2
SETFIT_UNCERTAINTY_HIGH = 0.8
SETFIT_ACCEPTANCE_LOW = 0.4
SETFIT_ACCEPTANCE_HIGH = 0.6
SETFIT_DIVERSITY_SIM_THRESHOLD = 0.85
FASTEMBED_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"

# OpenTDB ensemble / combination experiment groups
OPENTDB_ENSEMBLE_TRAIN_N = 100
OPENTDB_ENSEMBLE_HOLDOUT_N = 100
ENSEMBLE_MAX_ITEMS_PER_REQUEST = 8
ENSEMBLE_EXPERT_MAX = 2
ENSEMBLE_EXPERT_MIN_SUPPORT = 8
ENSEMBLE_OVR_POS_THRESHOLD = 0.5
ENSEMBLE_EXPERT_SCREAM_THRESHOLD = 0.85
ENSEMBLE_OVR_TRAIN_IMBALANCE_MAX = 0.2
ENSEMBLE_TOPIC = "ensemble"
COMBINATION_TOPIC = "combination"
ENSEMBLE_OVR_MAX_ITERS = 2
COMBINATION_CASCADE_ITERS = 3
COMBINATION_GOOGLE_THINKING_LEVEL = "high"
# Binary CS vs Technology combination track (OpenTDB-only)
COMBINATION_BINARY_LABELS = (
    "0 Computer science, information, and general works",
    "6 Technology",
)
COMBINATION_BINARY_TRAIN_PER_CLASS = 10
COMBINATION_BINARY_HOLDOUT_N = 80

# Smart experiment group (OpenTDB + Gemini)
SMART_TOPIC = "smart"
SMART_REF_PERCENTILE = 0.10
SMART_PARALLEL_WORKERS = 5
SMART_MAX_IN_FLIGHT = 15
SMART_PARSE_MAX_RETRIES = 25
SMART_CREATIVE_TEMPERATURE = 1.0
SMART_CREATIVE_TOP_P = 0.95
SMART_SYNTHETIC_CAP = 50
SMART_CV_FOLDS = 5
SMART_CV_TRAIN_N = 80
SMART_CV_VAL_N = 20
SMART_BATCH_EXPANSION_N = 5
SMART_PARALLEL_STREAMS = 3
SMART_PAIRS_PER_STREAM = 2
SMART_ITERATIVE_ITERS = 3
