"""Shared limits and defaults for synthetic-hardnlp experiments."""

CONTEXT_MAX_CHARS = 8000
PROMPT_SAVE_MAX_CHARS = 2000
GENERATION_ABS_MAX_CHARS = 600
BATCH_MAX_EXEMPLARS = 10
BATCH_MAX_EXEMPLAR_CHARS = 2000
GENERATION_TEMPERATURE = 0.8
VALIDATOR_TEMPERATURE = 0.0
PARSE_MAX_RETRIES = 3
TARGET_COL = "Domain"
TEXT_FORMAT = "embedder"
CLASSIFIER = "modernbert_linear_probe"
MODERNBERT_MODEL_ID = "answerdotai/ModernBERT-base"
MODERNBERT_MAX_LENGTH = 2048
OLLAMA_MODEL_DEFAULT = "llama3:8b"
SYNTHETIC_CAP_DEFAULT = 250

# SetFit experiment group
SETFIT_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
SETFIT_CLASSIFIER = "setfit"
SETFIT_TRAIN_N = 100
SETFIT_SYNTHETIC_CAP = 30
SETFIT_MAX_ITEMS_PER_REQUEST = 3
GOOGLE_GEMMA_MODEL_DEFAULT = "gemma-4-31b-it"
GOOGLE_FLASH_MODEL_DEFAULT = "gemini-3.1-flash-lite"
SETFIT_UNCERTAINTY_LOW = 0.2
SETFIT_UNCERTAINTY_HIGH = 0.8
SETFIT_ACCEPTANCE_LOW = 0.4
SETFIT_ACCEPTANCE_HIGH = 0.6
SETFIT_DIVERSITY_SIM_THRESHOLD = 0.85
FASTEMBED_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
